apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/www/html
          name: local-pvc
  volumes:
    - name: local-pvc
      persistentVolumeClaim:
        claimName: local-pvc