apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: development
subjects:
  - name: "martin"
    kind: User
roleRef:
  name: developer-role
  kind: Role
  apiGroup: "rbac.authorization.k8s.io"
