apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  labels:
    run: jekyll
    namespace: development
spec:
  initContainers:
    - name: copy-jekyll-site
      image: kodekloud/jekyll
      command: ["jekyll", "new", "/site"]
      volumeMounts:
        - name: site
          mountPath: "/site"
  containers:
    - name: jekyll
      image: kodekloud/jekyll-serve
      ports:
        - containerPort: 4000
      volumeMounts:
        - name: site
          mountPath: "/site"
  volumes:
    - name: site
      persistentVolumeClaim:
        claimName: jekyll-site
