apiVersion: v1
kind: Pod
metadata:
  namespace: elastic-stack
  name: elastic-search
  labels:
    name: elastic-search
spec:
  containers:
    - name: elastic-search
      image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
