apiVersion: v1
kind: Pod
metadata:
  namespace: elastic-stack
  name: kibana
  labels:
    name: kibana
spec:
  containers:
    - name: kibana
      image: kibana:6.4.2
      env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
