apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  containers:
    - name: red-container
      image: busybox:1.28
      command:
        - sh
        - -c
        - echo The app is running! && sleep 3600
  initContainers:
    - name: warmup
      image: busybox
      command:
        - sh
        - -c
        - sleep 1200