apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  labels:
    name: ubuntu-sleeper
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu
      securityContext:
        capabilities:
          add: ["SYS_TIME", "NET_ADMIN"]