apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: marketing
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
      protocol: TCP
  selector:
    name: redis-pod
