apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  selector:
    matchLabels:
      name: alpine-pod
  replicas: 3
  template:
    metadata:
      labels:
        name: alpine-pod
    spec:
      containers:
        - name: alpine
          image: httpd:2.4-alpine


