apiVersion: v1
kind: Pod
metadata:
  name: metadata-limits
spec:
  containers:
  - name: metdata
    image: sunitparekh/metadata:v1.0
    ports:
    - containerPort: 8080
    env:
      - name: info.app.version
        value: "2.0.0"
    resources:
      requests:
        memory: "250Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"