apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: vote
spec:
  selector:
    matchLabels:
      app: vote-pod
  template:
    metadata:
      labels:
        app: vote-pod
    spec:
      containers:
        - name: vote-app
          image: kodekloud/examplevotingapp_vote:before
          ports:
            - containerPort: 80
