apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: beta-apps
  name: beta-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      run: beta-apps
  template:
    metadata:
      labels:
        run: beta-apps
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app_type
                    operator: In
                    values:
                      - beta
      containers:
        - name: beta-apps
          image: nginx