apiVersion: v1
kind: Pod
metadata:
  name: alpha
spec:
  containers:
    - name: alpha
      image: redis
  tolerations:
    - key: "app_type"
      value: "alpha"
      operator: "Equal"
      effect: "NoSchedule"